### ISSUE TITLE
Final test #2

### ISSUE THREAD

**Issue by ycombinator** [ycombinator/doggielytics#21]
Comment made by creator at creation time.

**Comment by ycombinator** [comment]
Comment made several seconds later by creator. Should not count as first response.

**Comment by ycombinator** [comment]
Another comment made a few seconds later by creator. Still should not count as first response.

**Comment by miiiiiche** [comment]
The last comment, maybe (but I'm fine leaving additional comments as needed)!

**Comment by ycombinator** [comment]
Another comment made by creator after a legitimate first response comment. This should not change the recorded first response time.

**Comment by miiiiiche** [comment]
An action, in the form of a comment!
